export const products = [
  // Categoria: Papel Antigrasa
  {
    id: 1,
    name: "Papel Antigrasa para Alimentos",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/arte.png",
  },
  // Categoria: Porta Productos
  {
    id: 2,
    name: "Cono Portavasos",
    category: "porta-productos",
    desc: "Cono diseñado para transportar múltiples vasos de manera segura.",
    dimensions: "17.5 x 8 x 16 cm",
    price: 12.50,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 3,
    name: "Cono pequeño",
    category: "porta-productos",
    desc: "Cono ideal para snacks y frituras.",
    dimensions: "7 x 7 x 15 cm",
    price: 7.00,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 4,
    name: "Cono grande",
    category: "porta-productos",
    desc: "Cono grande para porciones más generosas.",
    dimensions: "7 x 7 x 22 cm",
    price: 8.00,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 5,
    name: "Cono Gigante",
    category: "porta-productos",
    desc: "Cono gigante para eventos y grandes porciones.",
    dimensions: "9 x 9 x 33 cm",
    price: 10.00,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 15,
    name: "Porta Papas Grande",
    category: "porta-productos",
    desc: "Contenedor ideal para papas fritas y snacks.",
    dimensions: "7.5 x 2.5 x 15.5 cm",
    price: 8.50,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 16,
    name: "Porta Papas Pequeño",
    category: "porta-productos",
    desc: "Contenedor ideal para papas fritas y snacks.",
    dimensions: "6 x 3 x 11 cm",
    price: 6.50,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 17,
    name: "Porta Hot Dog",
    category: "porta-productos",
    desc: "Contenedor diseñado para hot dogs y similares.",
    dimensions: "18 x 6 x 4 cm",
    price: 5.50,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 18,
    name: "Porta Hamburguesa",
    category: "porta-productos",
    desc: "Contenedor diseñado para hamburguesas y similares.",
    dimensions: "9 x 5 x 9 cm",
    price: 5.50,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 19,
    name: "Porta Vasos",
    category: "porta-productos",
    desc: "Contenedor diseñado para transportar vasos de manera segura.",
    dimensions: "18 x 8 x 17 cm",
    price: 5.50,
    units: 25,
    image: "/assets/arte.png",
  },

  // Categoria: Recipientes Contenedores
  {
    id: 12,
    name: "Contenedor 1",
    category: "recipientes-contenedores",
    desc: "Contenedor ideal para alimentos y snacks.",
    dimensions: "19 x 12 x 8 cm",
    price: 5.75,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 13,
    name: "Contenedor 2",
    category: "recipientes-contenedores",
    desc: "Contenedor grande y resistente para envío de alimentos.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 6.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 14,
    name: "Contenedor 3",
    category: "recipientes-contenedores",
    desc: "Contenedor grande y resistente para envío de alimentos.",
    dimensions: "9 x 7 x 10.5 cm",
    price: 6.50,
    units: 25,
    image: "/assets/arte.png",
  },

  // Categoria: Canoas y Bandejas
  {
    id: 8,
    name: "Canoas 1",
    category: "canoas-bandejas",
    desc: "Caja tipo canoa para alimentos y snacks.",
    dimensions: "11.5 x 7.5 x 5.2 cm",
    price: 5.00,
    units: 100,
    image: "/assets/arte.png",
  },
  {
    id: 9,
    name: "Canoa 2",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "15 x 14 x 4 cm",
    price: 5.00,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 10,
    name: "Canoa 3",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "16.5 x 9 x 5 cm",
    price: 5.50,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 11,
    name: "Canoa 4",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "20 x 20 x 4.5 cm",
    price: 5.50,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 20,
    name: "Bandeja Bocaditos Alta",
    category: "canoas-bandejas",
    desc: "Bandeja ideal para servir bocaditos y aperitivos.",
    dimensions: "27 x 18 x 8 cm",
    price: 6.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 21,
    name: "Bandeja Bocaditos Baja",
    category: "canoas-bandejas",
    desc: "Bandeja ideal para servir bocaditos y aperitivos.",
    dimensions: "27.5 x 18.5 x 3 cm",
    price: 4.50,
    units: 25,
    image: "/assets/arte.png",
  },

  // Categoria: Delivery Box
  {
    id: 6,
    name: "Big Box",
    category: "delivery-box",
    desc: "Caja grande y resistente para envíos y delivery.",
    dimensions: "20 x 20 x 7 cm",
    price: 8.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 7,
    name: "Mega Big Box",
    category: "delivery-box",
    desc: "Caja extra grande para envíos voluminosos.",
    dimensions: "25 x 25 x 7.5 cm",
    price: 11.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 22,
    name: "Lonchera",
    category: "delivery-box",
    desc: "Contenedor ideal para llevar almuerzos y snacks.",
    dimensions: "20 x 12 x 13 cm",
    price: 15.00,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 23,
    name: "Cajita Cuadrada",
    category: "delivery-box",
    desc: "Contenedor ideal para pequeños alimentos y snacks.",
    dimensions: "12 x 12 x 8 cm",
    price: 7.00,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 24,
    name: "Cajita Rectangular",
    category: "delivery-box",
    desc: "Contenedor ideal para pequeños alimentos y snacks.",
    dimensions: "14 x 9.5 x 7 cm",
    price: 7.00,
    units: 50,
    image: "/assets/arte.png",
  },
  {
    id: 25,
    name: "Caja Combos",
    category: "delivery-box",
    desc: "Caja ideal para combos de alimentos y snacks.",
    dimensions: "27 x 18 x 8 cm",
    price: 8.50,
    units: 25,
    image: "/assets/arte.png",
  },

  // Categoria: Dulces y Bocaditos
  {
    id: 27,
    name: "Caja de 1 Cupcake",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar un cupcake de manera segura.",
    dimensions: "10 x 10 x 10 cm",
    price: 5.50,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 28,
    name: "Caja de 3 o 4 Cupcakes sin Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar tres cupcakes de manera segura.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 8.50,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 29,
    name: "Caja de 3 o 4 Cupcakes con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar tres cupcakes con ventana para mejor presentación.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 13.50,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 30,
    name: "Caja de 6 Cupcakes sin Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar seis cupcakes de manera segura.",
    dimensions: "27 x 18 x 8 cm",
    price: 10.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 31,
    name: "Mini Box con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja pequeña con ventana para pequeños productos.",
    dimensions: "23 x 4.5 x 4.5 cm",
    price: 5.50,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 32,
    name: "Box 1 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja mediana con ventana para productos variados.",
    dimensions: "19 x 12 x 8 cm",
    price: 11.50,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 33,
    name: "Box 2 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja grande con ventana para productos variados.",
    dimensions: "17.5 x 15.5 x 8.5 cm",
    price: 12.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 34,
    name: "Box 3 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja extra grande con ventana para productos variados.",
    dimensions: "20 x 20 x 7 cm",
    price: 13.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 35,
    name: "Box 4 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja gigante con ventana para productos variados.",
    dimensions: "27 x 18 x 8 cm",
    price: 14.00,
    units: 25,
    image: "/assets/arte.png",
  },
  {
    id: 36,
    name: "Box 5 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja extra gigante con ventana para productos variados.",
    dimensions: "10 x 10 x 10 cm",
    price: 5.50,
    units: 25,
    image: "/assets/arte.png",
  },

  // Categoria: Extras
  {
    id: 26,
    name: "Stickers Personalizados",
    category: "extras",
    desc: "Stickers personalizados para tus empaques y productos.",
    dimensions: "5 x 5 cm",
    price: 2.00,
    units: 40,
    image: "/assets/arte.png",
  },
  {
    id: 37,
    name: "Caja para Botella de Vino sin Impresión",
    category: "extras",
    desc: "Contenedor diseñado para botellas de vino y similares.",
    dimensions: "8.5 x 8.5 x 38 cm",
    price: 4.75,
    units: 12,
    image: "/assets/arte.png",
  },
  {
    id: 38,
    name: "Caja para Botella de Vino con Impresión Genérica",
    category: "extras",
    desc: "Contenedor diseñado para botellas de vino y similares.",
    dimensions: "8.5 x 8.5 x 38 cm",
    price: 5.00,
    units: 12,
    image: "/assets/arte.png",
  },
  {
    id: 39,
    name: "Caja para Rosca de Reyes",
    category: "extras",
    desc: "Por implementar",
    dimensions: "—",
    price: 0,
    units: 0,
    image: "/assets/arte.png",
  },
]