export const products = [
  // Categoria: Papel Antigrasa
  {
    id: 1,
    name: "Papel Antigrasa para Alimentos - Modelo 1",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/papel-Antigrasa-1.png",
  },
  {
    id: 1001,
    name: "Papel Antigrasa para Alimentos - Modelo 2",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/papel-Antigrasa-2.png",
  },
  {
    id: 1002,
    name: "Papel Antigrasa para Alimentos - Modelo 3",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/papel-Antigrasa-3.png",
  },
  {
    id: 1003,
    name: "Papel Antigrasa para Alimentos - Modelo 4",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/papel-Antigrasa-4.png",
  },
  {
    id: 1004,
    name: "Papel Antigrasa para Alimentos - Modelo 5",
    category: "papel-antigrasa",
    desc: "Papel especial resistente a la grasa, ideal para envolver alimentos.",
    dimensions: "35 x 33 cm",
    price: 5.00,
    units: 100,
    image: "/assets/papel-Antigrasa-5.png",
  },
  // Categoria: Porta Productos
  {
    id: 2,
    name: "Cono Portavasos",
    category: "porta-productos",
    desc: "Cono diseñado para transportar múltiples vasos de manera segura.",
    dimensions: "17.5 x 8 x 16 cm",
    price: 12.50,
    units: 50,
    image: "/assets/conoPortavaso.png",
  },
  {
    id: 3,
    name: "Cono pequeño",
    category: "porta-productos",
    desc: "Cono ideal para snacks y frituras.",
    dimensions: "7 x 7 x 15 cm",
    price: 7.00,
    units: 100,
    image: "/assets/conoPequeño.png",
  },
  {
    id: 4,
    name: "Cono grande",
    category: "porta-productos",
    desc: "Cono grande para porciones más generosas.",
    dimensions: "7 x 7 x 22 cm",
    price: 8.00,
    units: 100,
    image: "/assets/conoGrande.png",
  },
  {
    id: 5,
    name: "Cono Gigante",
    category: "porta-productos",
    desc: "Cono gigante para eventos y grandes porciones.",
    dimensions: "9 x 9 x 33 cm",
    price: 10.00,
    units: 100,
    image: "/assets/conoGigante.png",
  },
  {
    id: 15,
    name: "Porta Papas Grande",
    category: "porta-productos",
    desc: "Contenedor ideal para papas fritas y snacks.",
    dimensions: "7.5 x 2.5 x 15.5 cm",
    price: 8.50,
    units: 100,
    image: "/assets/portaPapasGrande.png",
  },
  {
    id: 16,
    name: "Porta Papas Pequeño",
    category: "porta-productos",
    desc: "Contenedor ideal para papas fritas y snacks.",
    dimensions: "6 x 3 x 11 cm",
    price: 6.50,
    units: 100,
    image: "/assets/portaPapasPequeño.png",
  },
  {
    id: 17,
    name: "Porta Hot Dog",
    category: "porta-productos",
    desc: "Contenedor diseñado para hot dogs y similares.",
    dimensions: "18 x 6 x 4 cm",
    price: 5.50,
    units: 100,
    image: "/assets/portaHotDog.png",
  },
  {
    id: 18,
    name: "Porta Hamburguesa",
    category: "porta-productos",
    desc: "Contenedor diseñado para hamburguesas y similares.",
    dimensions: "9 x 5 x 9 cm",
    price: 5.50,
    units: 100,
    image: "/assets/portaHamburguesa.png",
  },
  {
    id: 19,
    name: "Porta Vasos",
    category: "porta-productos",
    desc: "Contenedor diseñado para transportar vasos de manera segura.",
    dimensions: "18 x 8 x 17 cm",
    price: 5.50,
    units: 25,
    image: "/assets/portaVasos.png",
  },

  // Categoria: Recipientes Contenedores
  {
    id: 12,
    name: "Contenedor 1",
    category: "recipientes-contenedores",
    desc: "Contenedor ideal para alimentos y snacks.",
    dimensions: "19 x 12 x 8 cm",
    price: 5.75,
    units: 25,
    image: "/assets/Contenedor01.png",
  },
  {
    id: 13,
    name: "Contenedor 2",
    category: "recipientes-contenedores",
    desc: "Contenedor grande y resistente para envío de alimentos.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 6.00,
    units: 25,
    image: "/assets/Contenedor02.png",
  },
  {
    id: 14,
    name: "Contenedor 3",
    category: "recipientes-contenedores",
    desc: "Contenedor grande y resistente para envío de alimentos.",
    dimensions: "9 x 7 x 10.5 cm",
    price: 6.50,
    units: 25,
    image: "/assets/Contenedor03.png",
  },

  // Categoria: Canoas y Bandejas
  {
    id: 8,
    name: "Canoa 1",
    category: "canoas-bandejas",
    desc: "Caja tipo canoa para alimentos y snacks.",
    dimensions: "11.5 x 7.5 x 5.2 cm",
    price: 5.00,
    units: 100,
    image: "/assets/Canoa01.png",
  },
  {
    id: 9,
    name: "Canoa 2",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "15 x 14 x 4 cm",
    price: 5.00,
    units: 50,
    image: "/assets/Canoa02.png",
  },
  {
    id: 10,
    name: "Canoa 3",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "16.5 x 9 x 5 cm",
    price: 5.50,
    units: 50,
    image: "/assets/Canoa03.png",
  },
  {
    id: 11,
    name: "Canoa 4",
    category: "canoas-bandejas",
    desc: "Caja grande y resistente para envíos pesados.",
    dimensions: "20 x 20 x 4.5 cm",
    price: 5.50,
    units: 50,
    image: "/assets/Canoa04.png",
  },
  {
    id: 20,
    name: "Bandeja Bocaditos Alta",
    category: "canoas-bandejas",
    desc: "Bandeja ideal para servir bocaditos y aperitivos.",
    dimensions: "27 x 18 x 8 cm",
    price: 6.00,
    units: 25,
    image: "/assets/BandejaBocaditosAlta.png",
  },
  {
    id: 21,
    name: "Bandeja Bocaditos Baja",
    category: "canoas-bandejas",
    desc: "Bandeja ideal para servir bocaditos y aperitivos.",
    dimensions: "27.5 x 18.5 x 3 cm",
    price: 4.50,
    units: 25,
    image: "/assets/BandejaBocaditosBaja.png",
  },

  // Categoria: Delivery Box
  {
    id: 6,
    name: "Big Box",
    category: "delivery-box",
    desc: "Caja grande y resistente para envíos y delivery.",
    dimensions: "20 x 20 x 7 cm",
    price: 8.00,
    units: 25,
    image: "/assets/BigBox.png",
  },
  {
    id: 7,
    name: "Mega Big Box",
    category: "delivery-box",
    desc: "Caja extra grande para envíos voluminosos.",
    dimensions: "25 x 25 x 7.5 cm",
    price: 11.00,
    units: 25,
    image: "/assets/MegaBigBox.png",
  },
  {
    id: 38,
    name: "Gigante Big Box",
    category: "delivery-box",
    desc: "Caja extra grande para envíos voluminosos.",
    dimensions: "25 x 25 x 7.5 cm",
    price: 11.00,
    units: 25,
    image: "/assets/MegaBigBox.png",
  },
  {
    id: 22,
    name: "Lonchera",
    category: "delivery-box",
    desc: "Contenedor ideal para llevar almuerzos y snacks.",
    dimensions: "20 x 12 x 13 cm",
    price: 15.00,
    units: 50,
    image: "/assets/Lonchera.png",
  },
  {
    id: 23,
    name: "Cajita Cuadrada",
    category: "delivery-box",
    desc: "Contenedor ideal para pequeños alimentos y snacks.",
    dimensions: "12 x 12 x 8 cm",
    price: 7.00,
    units: 50,
    image: "/assets/cajitaCuadrada.png",
  },
  {
    id: 24,
    name: "Cajita Rectangular",
    category: "delivery-box",
    desc: "Contenedor ideal para pequeños alimentos y snacks.",
    dimensions: "14 x 9.5 x 7 cm",
    price: 7.00,
    units: 50,
    image: "/assets/cajitaRectangular.png",
  },
  {
    id: 25,
    name: "Caja Combos",
    category: "delivery-box",
    desc: "Caja ideal para combos de alimentos y snacks.",
    dimensions: "27 x 18 x 8 cm",
    price: 8.50,
    units: 25,
    image: "/assets/cajaCombos.png",
  },

  // Categoria: Dulces y Bocaditos
  {
    id: 27,
    name: "Porta Cupcakes",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar un cupcake de manera segura.",
    dimensions: "10 x 10 x 10 cm",
    price: 8.00,
    units: 25,
    image: "/assets/portaCupcakes.png",
  },
  {
    id: 28,
    name: "Caja de 3 o 4 Cupcakes sin Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar tres cupcakes de manera segura.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 8.50,
    units: 25,
    image: "/assets/tresCupcakes.png",
  },
  {
    id: 29,
    name: "Caja de 3 o 4 Cupcakes con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar tres cupcakes con ventana para mejor presentación.",
    dimensions: "17.5 x 15 x 8.5 cm",
    price: 13.50,
    units: 25,
    image: "/assets/cuatroCupcakes.png",
  },
  {
    id: 30,
    name: "Caja de 6 Cupcakes sin Ventana",
    category: "dulces-bocaditos",
    desc: "Caja ideal para transportar seis cupcakes de manera segura.",
    dimensions: "27 x 18 x 8 cm",
    price: 10.00,
    units: 25,
    image: "/assets/seisCupcakes.png",
  },
  {
    id: 31,
    name: "Mini Box con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja pequeña con ventana para pequeños productos.",
    dimensions: "23 x 4.5 x 4.5 cm",
    price: 8.00,
    units: 25,
    image: "/assets/MiniBoxConVentana.png",
  },
  {
    id: 32,
    name: "Box 1 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja mediana con ventana para productos variados.",
    dimensions: "19 x 12 x 8 cm",
    price: 11.50,
    units: 25,
    image: "/assets/BoxConVentana01.png",
  },
  {
    id: 33,
    name: "Box 2 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja grande con ventana para productos variados.",
    dimensions: "17.5 x 15.5 x 8.5 cm",
    price: 12.00,
    units: 25,
    image: "/assets/BoxConVentana02.png",
  },
  {
    id: 34,
    name: "Box 3 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja extra grande con ventana para productos variados.",
    dimensions: "20 x 20 x 7 cm",
    price: 13.00,
    units: 25,
    image: "/assets/BoxConVentana03.png",
  },
  {
    id: 35,
    name: "Box 4 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja gigante con ventana para productos variados.",
    dimensions: "27 x 18 x 8 cm",
    price: 14.00,
    units: 25,
    image: "/assets/BoxConVentana04.png",
  },
  {
    id: 36,
    name: "Box 5 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja extra gigante con ventana para productos variados.",
    dimensions: "10 x 10 x 10 cm",
    price: 7.50,
    units: 25,
    image: "/assets/BoxConVentana05.png",
  },
  {
    id: 55,
    name: "Box 6 con Ventana",
    category: "dulces-bocaditos",
    desc: "Caja mediana con ventana para productos variados.",
    dimensions: "31 x 31 x 8 cm",
    price: 16.00,
    units: 25,
    image: "/assets/BoxConVentana06.png",
  },

  // Categoria: Extras
  {
    id: 26,
    name: "Stickers Personalizados (3x3 cm)",
    category: "extras",
    desc: "Stickers personalizados para tus empaques y productos. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "3 x 3 cm",
    price: 2.00,
    units: 115,
    image: "/assets/StickersPersonalizados.png",
  },
  {
    id: 261,
    name: "Stickers Personalizados (5x5 cm)",
    category: "extras",
    desc: "Stickers personalizados para tus empaques y productos. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "5 x 5 cm",
    price: 2.00,
    units: 40,
    image: "/assets/StickersPersonalizados.png",
  },
  {
    id: 262,
    name: "Stickers Personalizados (10x10 cm)",
    category: "extras",
    desc: "Stickers personalizados para tus empaques y productos. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "10 x 10 cm",
    price: 2.00,
    units: 12,
    image: "/assets/StickersPersonalizados.png",
  },
  {
    id: 37,
    name: "Caja para Botella de Vino sin Impresión",
    category: "extras",
    desc: "Contenedor diseñado para botellas de vino y similares.",
    dimensions: "8.5 x 8.5 x 38 cm",
    price: 4.75,
    units: 12,
    image: "/assets/botella-vino-sin-impresion.png",
  },
  
  // Categoria: Para Pizza
  {
    id: 41,
    name: "Porta Pizza",
    category: "para-pizza",
    desc: "Por implementar",
    dimensions: "20 x 14 x 1,5 cm",
    price: 4.00,
    units: 100,
    image: "/assets/portaPizza.png",
  },
  {
    id: 42,
    name: "Caja para Pizza 20 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "20 x 20 x 4.2 cm",
    price: 0.38,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 43,
    name: "Caja para Pizza 22 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "22 x 22 x 4.2 cm",
    price: 0.40,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 44,
    name: "Caja para Pizza 26 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "26 x 26 x 4.2 cm",
    price: 0.50,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 45,
    name: "Caja para Pizza 29 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "29 x 29 x 4.2 cm",
    price: 0.55,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 46,
    name: "Caja para Pizza 31 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "31 x 31 x 4.2 cm",
    price: 0.63,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 47,
    name: "Caja para Pizza 34 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "34 x 34 x 4.2 cm",
    price: 0.70,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 48,
    name: "Caja para Pizza 36 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "36 x 36 x 4.2 cm",
    price: 0.76,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 49,
    name: "Caja para Pizza 38 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "38 x 38 x 4.2 cm",
    price: 0.81,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 50,
    name: "Caja para Pizza 40 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "40 x 40 x 4.2 cm",
    price: 0.88,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 51,
    name: "Caja para Pizza 42 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "42 x 42 x 4.2 cm",
    price: 0.93,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 52,
    name: "Caja para Pizza 48 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "48 x 48 x 4.2 cm",
    price: 1.13,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 53,
    name: "Caja para Pizza 52 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "52 x 52 x 4.2 cm",
    price: 1.32,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
  {
    id: 54,
    name: "Caja para Pizza 60 cm",
    category: "para-pizza",
    desc: "Caja para pizza de varios tamaños. No hay mínimo de compra desde 1 caja en adelante. Entrega a domicilio Quito $3.00. Envíos a todo el país.",
    dimensions: "60 x 60 x 4.2 cm",
    price: 1.82,
    units: 1,
    image: "/assets/caja-pizza.png",
  },
]